export default [
  {
    name: "Lawn Mowing",
    ticketPrice: 30,
    _id: "1",
    Country: "USA",
    description: "Have a carpet-like lawn without any work.",
    Genre: [],
    Photo: "borat-subsequent-moviefilm-2020.jpg",
    rating: 5,
  },
  {
    name: "Lawn Mowing",
    ticketPrice: 50,
    _id: "2",
    Country: "USA",
    description: "Have a carpet-like lawn without any work.",
    Genre: [],
    Photo: "chintu-ka-birthday-2020.jpg",
    rating: 5,
  },
  {
    name: "Lawn Mowing",
    ticketPrice: 40,
    _id: "3",
    Country: "USA",
    description: "Have a carpet-like lawn without any work.",
    Genre: [],
    Photo: "city-of-salt-2020.jpg",
    rating: 5,
  },
  {
    name: "Lawn Mowing",
    ticketPrice: 100,
    _id: "4",
    Country: "USA",
    description: "Have a carpet-like lawn without any work.",
    Genre: [],
    Photo: "dau-degeneratsiya-2020.jpg",
    rating: 5,
  },
  {
    name: "Lawn Mowing",
    ticketPrice: 100,
    _id: "5",
    Country: "USA",
    description: "Have a carpet-like lawn without any work.",
    Genre: [],
    Photo:
      "dave-chappelle-the-kennedy-center-mark-twain-prize-for-american-humor-2020.jpg",
    rating: 5,
  },
  {
    name: "Lawn Mowing",
    ticketPrice: 100,
    _id: "6",
    Country: "USA",
    description: "Have a carpet-like lawn without any work.",
    Genre: [],
    Photo: "dil-bechara-2020.jpg",
    rating: 5,
  },
  {
    name: "Lawn Mowing",
    ticketPrice: 100,
    _id: "7",
    Country: "USA",
    description: "Have a carpet-like lawn without any work.",
    Genre: [],
    Photo: "faith-based-2020.jpg",
    rating: 5,
  },
  {
    name: "Lawn Mowing",
    ticketPrice: 100,
    _id: "8",
    Country: "USA",
    description: "Have a carpet-like lawn without any work.",
    Genre: [],
    Photo: "im-thinking-of-ending-things-2020.jpg",
    rating: 5,
  },
  {
    name: "Lawn Mowing",
    ticketPrice: 100,
    _id: "9",
    Country: "USA",
    description: "Have a carpet-like lawn without any work.",
    Genre: [],
    Photo: "midnight-delight-2016.jpg",
    rating: 5,
  },
  {
    name: "Lawn Mowing",
    ticketPrice: 100,
    _id: "10",
    Country: "USA",
    description: "Have a carpet-like lawn without any work.",
    Genre: [],
    Photo: "still-here-2020.jpg",
    rating: 5,
  },
];
